In [1]:
import os
import pandas as pd
import numpy as np

path = '/home/nikita/course/'
file = os.listdir(path)
df = pd.read_csv(path +'/' +file[0])

df['result'] = df['sentiment'].map({'positive' : 1, 'negative' : 0}).fillna(0)
df = df.drop('sentiment', axis=1)

df

                                                  review  result
0      One of the other reviewers has mentioned that ...       1
1      A wonderful little production. <br /><br />The...       1
2      I thought this was a wonderful way to spend ti...       1
3      Basically there's a family where a little boy ...       0
4      Petter Mattei's "Love in the Time of Money" is...       1
...                                                  ...     ...
49995  I thought this movie did a down right good job...       1
49996  Bad plot, bad dialogue, bad acting, idiotic di...       0
49997  I am a Catholic taught in parochial elementary...       0
49998  I'm going to have to disagree with the previou...       0
49999  No one expects the Star Trek movies to be high...       0

[50000 rows x 2 columns]

In [2]:
import nltk
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize
from nltk.stem import WordNetLemmatizer

In [3]:
text = df['review'][49999]

tokens = word_tokenize(text)

print('-----text----------')
print(text)
print('-----tokens----------')
print(tokens)

-----text----------
No one expects the Star Trek movies to be high art, but the fans do expect a movie that is as good as some of the best episodes. Unfortunately, this movie had a muddled, implausible plot that just left me cringing - this is by far the worst of the nine (so far) movies. Even the chance to watch the well known characters interact in another movie can't save this movie - including the goofy scenes with Kirk, Spock and McCoy at Yosemite.<br /><br />I would say this movie is not worth a rental, and hardly worth watching, however for the True Fan who needs to see all the movies, renting this movie is about the only way you'll see it - even the cable channels avoid this movie.
-----tokens----------
['No', 'one', 'expects', 'the', 'Star', 'Trek', 'movies', 'to', 'be', 'high', 'art', ',', 'but', 'the', 'fans', 'do', 'expect', 'a', 'movie', 'that', 'is', 'as', 'good', 'as', 'some', 'of', 'the', 'best', 'episodes', '.', 'Unfortunately', ',', 'this', 'movie', 'had', 'a', 'muddled', ',', 'implausible', 'plot', 'that', 'just', 'left', 'me', 'cringing', '-', 'this', 'is', 'by', 'far', 'the', 'worst', 'of', 'the', 'nine', '(', 'so', 'far', ')', 'movies', '.', 'Even', 'the', 'chance', 'to', 'watch', 'the', 'well', 'known', 'characters', 'interact', 'in', 'another', 'movie', 'ca', "n't", 'save', 'this', 'movie', '-', 'including', 'the', 'goofy', 'scenes', 'with', 'Kirk', ',', 'Spock', 'and', 'McCoy', 'at', 'Yosemite.', '<', 'br', '/', '>', '<', 'br', '/', '>', 'I', 'would', 'say', 'this', 'movie', 'is', 'not', 'worth', 'a', 'rental', ',', 'and', 'hardly', 'worth', 'watching', ',', 'however', 'for', 'the', 'True', 'Fan', 'who', 'needs', 'to', 'see', 'all', 'the', 'movies', ',', 'renting', 'this', 'movie', 'is', 'about', 'the', 'only', 'way', 'you', "'ll", 'see', 'it', '-', 'even', 'the', 'cable', 'channels', 'avoid', 'this', 'movie', '.']

In [4]:
nltk.download('punkt')
nltk.download('stopwords')
nltk.download('wordnet')
nltk.download('punkt_tab')

stop_words = set(stopwords.words('english'))
filtered_tokens = [word for word in tokens if word.lower() not in stop_words]

lemmatizer = WordNetLemmatizer()
lemmatized_tokens = [lemmatizer.lemmatize(word) for word in filtered_tokens]

print ('-----NLTK----------')
print ('-------------------')
print('-----text----------')
print(text)
print('-----filtered_tokens----------')
print(' '.join(filtered_tokens))
print('-----lemmatized_tokens----------')
print(' '.join(lemmatized_tokens))

[nltk_data] Downloading package punkt to /home/nikita/nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package stopwords to /home/nikita/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package wordnet to /home/nikita/nltk_data...
[nltk_data]   Package wordnet is already up-to-date!
[nltk_data] Downloading package punkt_tab to /home/nikita/nltk_data...
[nltk_data]   Package punkt_tab is already up-to-date!

-----NLTK----------
-------------------
-----text----------
No one expects the Star Trek movies to be high art, but the fans do expect a movie that is as good as some of the best episodes. Unfortunately, this movie had a muddled, implausible plot that just left me cringing - this is by far the worst of the nine (so far) movies. Even the chance to watch the well known characters interact in another movie can't save this movie - including the goofy scenes with Kirk, Spock and McCoy at Yosemite.<br /><br />I would say this movie is not worth a rental, and hardly worth watching, however for the True Fan who needs to see all the movies, renting this movie is about the only way you'll see it - even the cable channels avoid this movie.
-----filtered_tokens----------
one expects Star Trek movies high art , fans expect movie good best episodes . Unfortunately , movie muddled , implausible plot left cringing - far worst nine ( far ) movies . Even chance watch well known characters interact another movie ca n't save movie - including goofy scenes Kirk , Spock McCoy Yosemite. < br / > < br / > would say movie worth rental , hardly worth watching , however True Fan needs see movies , renting movie way 'll see - even cable channels avoid movie .
-----lemmatized_tokens----------
one expects Star Trek movie high art , fan expect movie good best episode . Unfortunately , movie muddled , implausible plot left cringing - far worst nine ( far ) movie . Even chance watch well known character interact another movie ca n't save movie - including goofy scene Kirk , Spock McCoy Yosemite. < br / > < br / > would say movie worth rental , hardly worth watching , however True Fan need see movie , renting movie way 'll see - even cable channel avoid movie .

In [5]:
import spacy

nlp = spacy.load("en_core_web_sm")

# Обработка текста с автоматической лемматизацией
doc = nlp(text)

print ('-----SPACY----------')
print ('-------------------')
print('-----text----------')
print(text)
print('-----filtered and lemmatized tokens----------')
print(' '.join([token.lemma_ for token in doc]))

-----SPACY----------
-------------------
-----text----------
No one expects the Star Trek movies to be high art, but the fans do expect a movie that is as good as some of the best episodes. Unfortunately, this movie had a muddled, implausible plot that just left me cringing - this is by far the worst of the nine (so far) movies. Even the chance to watch the well known characters interact in another movie can't save this movie - including the goofy scenes with Kirk, Spock and McCoy at Yosemite.<br /><br />I would say this movie is not worth a rental, and hardly worth watching, however for the True Fan who needs to see all the movies, renting this movie is about the only way you'll see it - even the cable channels avoid this movie.
-----filtered and lemmatized tokens----------
no one expect the Star Trek movie to be high art , but the fan do expect a movie that be as good as some of the good episode . unfortunately , this movie have a muddle , implausible plot that just leave I cringe - this be by far the bad of the nine ( so far ) movie . even the chance to watch the well know character interact in another movie can not save this movie - include the goofy scene with Kirk , Spock and McCoy at Yosemite.<br /><br />I would say this movie be not worth a rental , and hardly worth watch , however for the True Fan who need to see all the movie , rent this movie be about the only way you will see it - even the cable channel avoid this movie .

In [40]:
#для русского языка используем библиотеки pymorphy2, PyMystem3, Natasha

In [6]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [9]:
vectorizer = TfidfVectorizer()
X = vectorizer.fit_transform(lemmatized_tokens)
vectorizer.get_feature_names_out()

array(['another', 'art', 'avoid', 'best', 'br', 'ca', 'cable', 'chance',
       'channel', 'character', 'cringing', 'episode', 'even', 'expect',
       'expects', 'fan', 'far', 'good', 'goofy', 'hardly', 'high',
       'however', 'implausible', 'including', 'interact', 'kirk', 'known',
       'left', 'll', 'mccoy', 'movie', 'muddled', 'need', 'nine', 'one',
       'plot', 'rental', 'renting', 'save', 'say', 'scene', 'see',
       'spock', 'star', 'trek', 'true', 'unfortunately', 'watch',
       'watching', 'way', 'well', 'worst', 'worth', 'would', 'yosemite'],
      dtype=object)

In [10]:
X.toarray()

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 1., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [12]:
from sklearn.feature_extraction.text import CountVectorizer

proc_text = ' '.join(lemmatized_tokens)


vectorizer_bow = CountVectorizer()
X_bow = vectorizer_bow.fit_transform([proc_text]) 
feature_names_bow = vectorizer_bow.get_feature_names_out()
print("BoW матрица:", X_bow.toarray())
print(feature_names_bow)

BoW матрица: [[ 1  1  1  1  2  1  1  1  1  1  1  1  2  1  1  2  2  1  1  1  1  1  1  1
   1  1  1  1  1  1 10  1  1  1  1  1  1  1  1  1  1  2  1  1  1  1  1  1
   1  1  1  1  2  1  1]]
['another' 'art' 'avoid' 'best' 'br' 'ca' 'cable' 'chance' 'channel'
 'character' 'cringing' 'episode' 'even' 'expect' 'expects' 'fan' 'far'
 'good' 'goofy' 'hardly' 'high' 'however' 'implausible' 'including'
 'interact' 'kirk' 'known' 'left' 'll' 'mccoy' 'movie' 'muddled' 'need'
 'nine' 'one' 'plot' 'rental' 'renting' 'save' 'say' 'scene' 'see' 'spock'
 'star' 'trek' 'true' 'unfortunately' 'watch' 'watching' 'way' 'well'
 'worst' 'worth' 'would' 'yosemite']

In [14]:
import gensim.downloader as api

model_w2v = api.load('glove-wiki-gigaword-50')

[==================================================] 100.0% 66.0/66.0MB downloaded

In [16]:
doc_vec = np.mean([model_w2v[word] for word in lemmatized_tokens if word in model_w2v], axis=0)
print('размер векторов:', doc_vec.shape)
doc_vec[:5]

размер векторов: (50,)

array([0.17559277, 0.29413462, 0.14936419, 0.03039818, 0.26714233],
      dtype=float32)

In [18]:
df['tokens'] = df['review'].map(lambda x: word_tokenize(x))
df

,review,result,tokens
0,One of the other reviewers has mentioned that ...,1,"[One, of, the, other, reviewers, has, mentione..."
1,A wonderful little production. <br /><br />The...,1,"[A, wonderful, little, production, ., <, br, /..."
2,I thought this was a wonderful way to spend ti...,1,"[I, thought, this, was, a, wonderful, way, to,..."
3,Basically there's a family where a little boy ...,0,"[Basically, there, 's, a, family, where, a, li..."
4,"Petter Mattei's ""Love in the Time of Money"" is...",1,"[Petter, Mattei, 's, ``, Love, in, the, Time, ..."
...,...,...,...
49995,I thought this movie did a down right good job...,1,"[I, thought, this, movie, did, a, down, right,..."
49996,"Bad plot, bad dialogue, bad acting, idiotic di...",0,"[Bad, plot, ,, bad, dialogue, ,, bad, acting, ..."
49997,I am a Catholic taught in parochial elementary...,0,"[I, am, a, Catholic, taught, in, parochial, el..."
49998,I'm going to have to disagree with the previou...,0,"[I, 'm, going, to, have, to, disagree, with, t..."
49999,No one expects the Star Trek movies to be high...,0,"[No, one, expects, the, Star, Trek, movies, to..."

In [20]:
df['filtered_tokens'] = df['tokens'].map(lambda x: [word for word in x if word.lower() not in stop_words])
df

,review,result,tokens,filtered_tokens
0,One of the other reviewers has mentioned that ...,1,"[One, of, the, other, reviewers, has, mentione...","[One, reviewers, mentioned, watching, 1, Oz, e..."
1,A wonderful little production. <br /><br />The...,1,"[A, wonderful, little, production, ., <, br, /...","[wonderful, little, production, ., <, br, /, >..."
2,I thought this was a wonderful way to spend ti...,1,"[I, thought, this, was, a, wonderful, way, to,...","[thought, wonderful, way, spend, time, hot, su..."
3,Basically there's a family where a little boy ...,0,"[Basically, there, 's, a, family, where, a, li...","[Basically, 's, family, little, boy, (, Jake, ..."
4,"Petter Mattei's ""Love in the Time of Money"" is...",1,"[Petter, Mattei, 's, ``, Love, in, the, Time, ...","[Petter, Mattei, 's, ``, Love, Time, Money, ''..."
...,...,...,...,...
49995,I thought this movie did a down right good job...,1,"[I, thought, this, movie, did, a, down, right,...","[thought, movie, right, good, job, ., n't, cre..."
49996,"Bad plot, bad dialogue, bad acting, idiotic di...",0,"[Bad, plot, ,, bad, dialogue, ,, bad, acting, ...","[Bad, plot, ,, bad, dialogue, ,, bad, acting, ..."
49997,I am a Catholic taught in parochial elementary...,0,"[I, am, a, Catholic, taught, in, parochial, el...","[Catholic, taught, parochial, elementary, scho..."
49998,I'm going to have to disagree with the previou...,0,"[I, 'm, going, to, have, to, disagree, with, t...","['m, going, disagree, previous, comment, side,..."
49999,No one expects the Star Trek movies to be high...,0,"[No, one, expects, the, Star, Trek, movies, to...","[one, expects, Star, Trek, movies, high, art, ..."

In [21]:
df['lemmatized_tokens'] = df['filtered_tokens'].map(lambda x: ' '.join([lemmatizer.lemmatize(word) for word in x]))
df

,review,result,tokens,filtered_tokens,lemmatized_tokens
0,One of the other reviewers has mentioned that ...,1,"[One, of, the, other, reviewers, has, mentione...","[One, reviewers, mentioned, watching, 1, Oz, e...",One reviewer mentioned watching 1 Oz episode '...
1,A wonderful little production. <br /><br />The...,1,"[A, wonderful, little, production, ., <, br, /...","[wonderful, little, production, ., <, br, /, >...",wonderful little production . < br / > < br / ...
2,I thought this was a wonderful way to spend ti...,1,"[I, thought, this, was, a, wonderful, way, to,...","[thought, wonderful, way, spend, time, hot, su...",thought wonderful way spend time hot summer we...
3,Basically there's a family where a little boy ...,0,"[Basically, there, 's, a, family, where, a, li...","[Basically, 's, family, little, boy, (, Jake, ...",Basically 's family little boy ( Jake ) think ...
4,"Petter Mattei's ""Love in the Time of Money"" is...",1,"[Petter, Mattei, 's, ``, Love, in, the, Time, ...","[Petter, Mattei, 's, ``, Love, Time, Money, ''...",Petter Mattei 's `` Love Time Money '' visuall...
...,...,...,...,...,...
49995,I thought this movie did a down right good job...,1,"[I, thought, this, movie, did, a, down, right,...","[thought, movie, right, good, job, ., n't, cre...",thought movie right good job . n't creative or...
49996,"Bad plot, bad dialogue, bad acting, idiotic di...",0,"[Bad, plot, ,, bad, dialogue, ,, bad, acting, ...","[Bad, plot, ,, bad, dialogue, ,, bad, acting, ...","Bad plot , bad dialogue , bad acting , idiotic..."
49997,I am a Catholic taught in parochial elementary...,0,"[I, am, a, Catholic, taught, in, parochial, el...","[Catholic, taught, parochial, elementary, scho...",Catholic taught parochial elementary school nu...
49998,I'm going to have to disagree with the previou...,0,"[I, 'm, going, to, have, to, disagree, with, t...","['m, going, disagree, previous, comment, side,...",'m going disagree previous comment side Maltin...
49999,No one expects the Star Trek movies to be high...,0,"[No, one, expects, the, Star, Trek, movies, to...","[one, expects, Star, Trek, movies, high, art, ...","one expects Star Trek movie high art , fan exp..."

In [22]:
from sklearn.model_selection import train_test_split

X = df["lemmatized_tokens"].to_numpy()
y = df["result"].to_numpy()

X_train, X_temp, y_train, y_temp = train_test_split(X, y, test_size=0.3, random_state=42, stratify=y)
X_val, X_test, y_val, y_test = train_test_split(X_temp, y_temp, test_size=0.5, random_state=42, stratify=y_temp)

In [24]:
from gensim.downloader import load

w2v = load('glove-wiki-gigaword-50')

def doc_average(text, model):
    words = text.split()
    vectors = [model[w] for w in words if w in model]
    if vectors:
        return np.mean(vectors, axis=0)
    else:
        return np.zeros(model.vector_size)

X_train_dense = np.array([doc_average(t, w2v) for t in X_train])
X_val_dense = np.array([doc_average(t, w2v) for t in X_val])
X_test_dense = np.array([doc_average(t, w2v) for t in X_test])

In [26]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler(with_mean=True)
scaler.fit(X_train_dense)
X_train_scaled = scaler.transform(X_train_dense)
X_val_scaled = scaler.transform(X_val_dense)
X_test_scaled = scaler.transform(X_test_dense)

In [42]:
from sklearn.linear_model import LogisticRegression

lr = LogisticRegression(max_iter=1000)
lr.fit(X_train_scaled, y_train)
print('accuracy логистической регрессии для обучающей / тестовой выборки: ', round(lr.score(X_train_scaled, y_train), 2), ' / ', round(lr.score(X_test_scaled, y_test), 2))

accuracy логистической регрессии для обучающей / тестовой выборки:  0.77  /  0.76

In [43]:
from sklearn.ensemble import RandomForestClassifier

rf = RandomForestClassifier(n_estimators=100, random_state=42, max_depth=50, min_samples_leaf= 20)
rf.fit(X_train_scaled, y_train)
print('accuracy random forestдля обучающей / тестовой выборки: ', round(rf.score(X_train_scaled, y_train), 2), ' / ', round(rf.score(X_test_scaled, y_test), 2))

accuracy random forestдля обучающей / тестовой выборки:  0.85  /  0.75

In [44]:
import keras
from tensorflow.keras.callbacks import EarlyStopping
from tensorflow.keras import layers
import tensorflow as tf

print("Версия TensorFlow:", tf.__version__)
print("Доступные GPU:", tf.config.list_physical_devices('GPU'))
print("Устройство для вычислений:", tf.test.is_gpu_available())

Версия TensorFlow: 2.14.0
Доступные GPU: [PhysicalDevice(name='/physical_device:GPU:0', device_type='GPU')]
Устройство для вычислений: True

2026-04-17 21:24:33.162597: I tensorflow/compiler/xla/stream_executor/cuda/cuda_gpu_executor.cc:894] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero. See more at https://github.com/torvalds/linux/blob/v6.0/Documentation/ABI/testing/sysfs-bus-pci#L344-L355
2026-04-17 21:24:33.164929: I tensorflow/compiler/xla/stream_executor/cuda/cuda_gpu_executor.cc:894] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero. See more at https://github.com/torvalds/linux/blob/v6.0/Documentation/ABI/testing/sysfs-bus-pci#L344-L355
2026-04-17 21:24:33.166865: I tensorflow/compiler/xla/stream_executor/cuda/cuda_gpu_executor.cc:894] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero. See more at https://github.com/torvalds/linux/blob/v6.0/Documentation/ABI/testing/sysfs-bus-pci#L344-L355
2026-04-17 21:24:33.167847: I tensorflow/compiler/xla/stream_executor/cuda/cuda_gpu_executor.cc:894] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero. See more at https://github.com/torvalds/linux/blob/v6.0/Documentation/ABI/testing/sysfs-bus-pci#L344-L355
2026-04-17 21:24:33.168667: I tensorflow/compiler/xla/stream_executor/cuda/cuda_gpu_executor.cc:894] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero. See more at https://github.com/torvalds/linux/blob/v6.0/Documentation/ABI/testing/sysfs-bus-pci#L344-L355
2026-04-17 21:24:33.169465: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1886] Created device /device:GPU:0 with 9774 MB memory:  -> device: 0, name: NVIDIA GeForce RTX 4070 SUPER, pci bus id: 0000:06:00.0, compute capability: 8.9

In [56]:
model = keras.Sequential([
    keras.layers.Dense(128),
    keras.layers.Dense(64),
    keras.layers.Dropout(0.3),
    keras.layers.BatchNormalization(),
    keras.layers.Dense(64, activation ='relu'),
    keras.layers.BatchNormalization(),
    keras.layers.Dense(2, activation ='softmax')
])

model.compile(  optimizer = keras.optimizers.Adam(learning_rate = 3e-4),
                loss = 'sparse_categorical_crossentropy',
                metrics = ['accuracy']
                )

early_stopping = EarlyStopping(
                    monitor='val_loss',
                    mode='min',
                    patience = 20,
                    min_delta = 0.01,
                    verbose = 1,
                    restore_best_weights = True
                    )

In [58]:
model.fit(
        x = X_train_scaled,
        y = y_train,
        batch_size = 32,
        epochs = 2000,
        verbose = 0,
        callbacks = [early_stopping], 
        shuffle = True,
        validation_data = (X_val_scaled, y_val),
        validation_batch_size = 32
        )

Restoring model weights from the end of the best epoch: 1.
Epoch 21: early stopping

In [59]:
train_loss, keras_train_acc = model.evaluate(X_train_scaled, y_train)
test_loss, keras_test_acc = model.evaluate(X_test_scaled, y_test)
print('для полносвязной нейронной сети точность для обучающей \ тестовой выборки:', round(keras_train_acc, 2), ' \ ', round(keras_test_acc, 2))

1094/1094 [==============================] - 1s 871us/step - loss: 0.4553 - accuracy: 0.7877
235/235 [==============================] - 0s 899us/step - loss: 0.4732 - accuracy: 0.7760
для полносвязной нейронной сети точность для обучающей \ тестовой выборки: 0.79  \  0.78